
// This file has been generated by the GUI designer. Do not modify.
namespace SQLGrenadineGui
{
	public partial class ConnectionDialog
	{
		private global::Gtk.VBox vboxConnection;
		private global::Gtk.Label labelInfo;
		private global::Gtk.HBox hboxSelection;
		private global::Gtk.Label labelSelectDatabase;
		private global::Gtk.ComboBox comboboxSelectDatabase;
		private global::Gtk.Button buttonCancel;
		private global::Gtk.Button buttonOk;
        
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget SQLGrenadineGui.ConnectionDialog
			this.Name = "SQLGrenadineGui.ConnectionDialog";
			this.Title = global::Mono.Unix.Catalog.GetString ("Connection");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child SQLGrenadineGui.ConnectionDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.vboxConnection = new global::Gtk.VBox ();
			this.vboxConnection.Name = "vboxConnection";
			this.vboxConnection.Spacing = 6;
			// Container child vboxConnection.Gtk.Box+BoxChild
			this.labelInfo = new global::Gtk.Label ();
			this.labelInfo.Name = "labelInfo";
			this.labelInfo.LabelProp = global::Mono.Unix.Catalog.GetString ("<i>Choose the database type to connect and enter your connection credentials.</i>");
			this.labelInfo.UseMarkup = true;
			this.vboxConnection.Add (this.labelInfo);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vboxConnection [this.labelInfo]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vboxConnection.Gtk.Box+BoxChild
			this.hboxSelection = new global::Gtk.HBox ();
			this.hboxSelection.Name = "hboxSelection";
			this.hboxSelection.Spacing = 6;
			// Container child hboxSelection.Gtk.Box+BoxChild
			this.labelSelectDatabase = new global::Gtk.Label ();
			this.labelSelectDatabase.Name = "labelSelectDatabase";
			this.labelSelectDatabase.LabelProp = global::Mono.Unix.Catalog.GetString ("Choose database type:");
			this.hboxSelection.Add (this.labelSelectDatabase);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hboxSelection [this.labelSelectDatabase]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hboxSelection.Gtk.Box+BoxChild
			this.comboboxSelectDatabase = global::Gtk.ComboBox.NewText ();
			this.comboboxSelectDatabase.Name = "comboboxSelectDatabase";
			this.hboxSelection.Add (this.comboboxSelectDatabase);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hboxSelection [this.comboboxSelectDatabase]));
			w4.PackType = ((global::Gtk.PackType)(1));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			this.vboxConnection.Add (this.hboxSelection);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vboxConnection [this.hboxSelection]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			w1.Add (this.vboxConnection);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(w1 [this.vboxConnection]));
			w6.Position = 0;
			// Internal child SQLGrenadineGui.ConnectionDialog.ActionArea
			global::Gtk.HButtonBox w7 = this.ActionArea;
			w7.Name = "dialog1_ActionArea";
			w7.Spacing = 10;
			w7.BorderWidth = ((uint)(5));
			w7.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-cancel";
			this.AddActionWidget (this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w8 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w7 [this.buttonCancel]));
			w8.Expand = false;
			w8.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button ();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-ok";
			this.AddActionWidget (this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w9 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w7 [this.buttonOk]));
			w9.Position = 1;
			w9.Expand = false;
			w9.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 473;
			this.DefaultHeight = 300;
			this.Show ();
			this.comboboxSelectDatabase.Changed += new global::System.EventHandler (this.OnComboBoxChanged);
			this.buttonCancel.Clicked += new global::System.EventHandler (this.OnButtonClose);
			this.buttonOk.Clicked += new global::System.EventHandler (this.OnButtonOk);
		}
	}
}
