
// This file has been generated by the GUI designer. Do not modify.
namespace SQLGrenadineGui
{
	public partial class ErrorDialog
	{
		private global::Gtk.VBox vboxError;
		private global::Gtk.Label labelErrorTitle;
		private global::Gtk.HBox hboxErrorContent;
		private global::Gtk.Image imageErrorState;
		private global::Gtk.Label labelErrorMessage;
		private global::Gtk.Button buttonCancel;
		private global::Gtk.Button buttonOk;
        
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget SQLGrenadineGui.ErrorDialog
			this.Name = "SQLGrenadineGui.ErrorDialog";
			this.Title = global::Mono.Unix.Catalog.GetString ("Error");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child SQLGrenadineGui.ErrorDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.vboxError = new global::Gtk.VBox ();
			this.vboxError.Name = "vboxError";
			this.vboxError.Spacing = 6;
			// Container child vboxError.Gtk.Box+BoxChild
			this.labelErrorTitle = new global::Gtk.Label ();
			this.labelErrorTitle.Name = "labelErrorTitle";
			this.labelErrorTitle.Xalign = 0F;
			this.labelErrorTitle.LabelProp = global::Mono.Unix.Catalog.GetString ("Error title");
			this.vboxError.Add (this.labelErrorTitle);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vboxError [this.labelErrorTitle]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vboxError.Gtk.Box+BoxChild
			this.hboxErrorContent = new global::Gtk.HBox ();
			this.hboxErrorContent.Name = "hboxErrorContent";
			this.hboxErrorContent.Spacing = 6;
			// Container child hboxErrorContent.Gtk.Box+BoxChild
			this.imageErrorState = new global::Gtk.Image ();
			this.imageErrorState.Name = "imageErrorState";
			this.imageErrorState.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-dialog-warning", global::Gtk.IconSize.Dialog);
			this.hboxErrorContent.Add (this.imageErrorState);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hboxErrorContent [this.imageErrorState]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hboxErrorContent.Gtk.Box+BoxChild
			this.labelErrorMessage = new global::Gtk.Label ();
			this.labelErrorMessage.Name = "labelErrorMessage";
			this.labelErrorMessage.Xalign = 0F;
			this.labelErrorMessage.LabelProp = global::Mono.Unix.Catalog.GetString ("Error message");
			this.hboxErrorContent.Add (this.labelErrorMessage);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hboxErrorContent [this.labelErrorMessage]));
			w4.Position = 1;
			this.vboxError.Add (this.hboxErrorContent);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vboxError [this.hboxErrorContent]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			w1.Add (this.vboxError);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(w1 [this.vboxError]));
			w6.Position = 0;
			w6.Expand = false;
			w6.Fill = false;
			// Internal child SQLGrenadineGui.ErrorDialog.ActionArea
			global::Gtk.HButtonBox w7 = this.ActionArea;
			w7.Name = "dialog1_ActionArea";
			w7.Spacing = 10;
			w7.BorderWidth = ((uint)(5));
			w7.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-cancel";
			this.AddActionWidget (this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w8 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w7 [this.buttonCancel]));
			w8.Expand = false;
			w8.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button ();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-ok";
			this.AddActionWidget (this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w9 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w7 [this.buttonOk]));
			w9.Position = 1;
			w9.Expand = false;
			w9.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 196;
			this.Show ();
		}
	}
}
