
// This file has been generated by the GUI designer. Do not modify.
namespace SQLGrenadineGui
{
	public partial class QueryWidget
	{
		private global::Gtk.VPaned vpanedContent;
		private global::Gtk.ScrolledWindow GtkScrolledWindow1;
		private global::Gtk.TextView textviewEditor;
		private global::Gtk.VPaned vpanedResult;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.TreeView treeviewResult;
		private global::Gtk.ScrolledWindow GtkScrolledWindow2;
		private global::Gtk.TextView textviewMessage;
        
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget SQLGrenadineGui.QueryWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "SQLGrenadineGui.QueryWidget";
			// Container child SQLGrenadineGui.QueryWidget.Gtk.Container+ContainerChild
			this.vpanedContent = new global::Gtk.VPaned ();
			this.vpanedContent.CanFocus = true;
			this.vpanedContent.Name = "vpanedContent";
			this.vpanedContent.Position = 198;
			// Container child vpanedContent.Gtk.Paned+PanedChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.textviewEditor = new global::Gtk.TextView ();
			this.textviewEditor.CanFocus = true;
			this.textviewEditor.Name = "textviewEditor";
			this.GtkScrolledWindow1.Add (this.textviewEditor);
			this.vpanedContent.Add (this.GtkScrolledWindow1);
			global::Gtk.Paned.PanedChild w2 = ((global::Gtk.Paned.PanedChild)(this.vpanedContent [this.GtkScrolledWindow1]));
			w2.Resize = false;
			// Container child vpanedContent.Gtk.Paned+PanedChild
			this.vpanedResult = new global::Gtk.VPaned ();
			this.vpanedResult.CanFocus = true;
			this.vpanedResult.Name = "vpanedResult";
			this.vpanedResult.Position = 144;
			// Container child vpanedResult.Gtk.Paned+PanedChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.treeviewResult = new global::Gtk.TreeView ();
			this.treeviewResult.CanFocus = true;
			this.treeviewResult.Name = "treeviewResult";
			this.GtkScrolledWindow.Add (this.treeviewResult);
			this.vpanedResult.Add (this.GtkScrolledWindow);
			global::Gtk.Paned.PanedChild w4 = ((global::Gtk.Paned.PanedChild)(this.vpanedResult [this.GtkScrolledWindow]));
			w4.Resize = false;
			// Container child vpanedResult.Gtk.Paned+PanedChild
			this.GtkScrolledWindow2 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
			this.GtkScrolledWindow2.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
			this.textviewMessage = new global::Gtk.TextView ();
			this.textviewMessage.CanFocus = true;
			this.textviewMessage.Name = "textviewMessage";
			this.GtkScrolledWindow2.Add (this.textviewMessage);
			this.vpanedResult.Add (this.GtkScrolledWindow2);
			this.vpanedContent.Add (this.vpanedResult);
			this.Add (this.vpanedContent);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.textviewEditor.KeyReleaseEvent += new global::Gtk.KeyReleaseEventHandler (this.OnKeyReleased);
		}
	}
}
